// this file is generated by gulp task ^_^

import getCookie from './getCookie.js'
import getLocalStorage from './getLocalStorage.js'
import hasValue from './hasValue.js'
import setCookie from './setCookie.js'
import setLocalStorage from './setLocalStorage.js'
import validateIdCardNo from './validateIdCardNo.js'

export default {
  getCookie,
  getLocalStorage,
  hasValue,
  setCookie,
  setLocalStorage,
  validateIdCardNo
}
